<?php
/**
 * SeDaP Bilingual Localization Engine (Bahasa Melayu & English)
 */

if (!isset($_SESSION)) {
    session_start();
}

if (!function_exists('sedap_root')) {
    function sedap_root(): string {
        if (!empty($_SERVER['SCRIPT_NAME'])) {
            $script = str_replace('\\', '/', $_SERVER['SCRIPT_NAME']);
            $pos = strpos($script, '/pages/');
            if ($pos !== false) {
                return substr($script, 0, $pos);
            }
            $dir = dirname($script);
            return ($dir === '/' || $dir === '\\') ? '' : str_replace('\\', '/', $dir);
        }
        return '/sedap/sedap2.0';
    }
}
if (!isset($_ROOT)) {
    $_ROOT = sedap_root();
}

$_SESSION_LANG = $_SESSION['lang'] ?? 'ms';
if (!in_array($_SESSION_LANG, ['ms', 'en'], true)) {
    $_SESSION_LANG = 'ms';
}

$TRANSLATIONS = [
    'ms' => [
        'settings_sound_test' => 'Uji Bunyi',
        'settings_sound_desc' => 'Mainkan nada amaran klinikal apabila mesej atau pesakit baharu tiba',
        'settings_sound_msg' => 'Bunyi Notifikasi Mesej Baharu',
        'settings_sound_title' => 'Notifikasi & Bunyi Mesej',
        'btn_copy' => 'Salin Teks',
        'btn_remove_photo' => 'Padam / Batal Foto',
        'btn_upload_photo' => 'Muat Naik Foto',
        'modal_video_title' => 'Tele-Konsultasi Video Perubatan Selamat',
        'modal_history_title' => 'Sejarah Triaj Pesakit',
        'modal_faq_sub' => 'Pilih protokol perubatan yang disahkan untuk dimasukkan ke dalam konsultasi:',
        'modal_faq_title' => 'Templat FAQ & Respons Pantas Klinikal',
        'ph_type_message' => 'Tulis mesej...',
        'chip_send_article' => 'Hantar Artikel',
        'chip_request_photo' => 'Minta Foto',
        'chip_faq_templates' => 'Templat FAQ',
        'btn_escalate_video' => 'Panggilan Video',
        'btn_history' => 'Rekod',
        'triage_queue_title' => 'Giliran Triaj (Triage Queue)',
        'status_controlled' => 'Kawalan Ketat',
        'lop_dosage_desc' => 'Atas preskripsi doktor sahaja',
        'cat_antidiarrheal' => 'Antidiarrheal',
        'meto_dosage_desc' => '1 biji 3 kali sehari sebelum makan',
        'cat_antiemetic' => 'Antiemetik',
        'pcm_dosage_desc' => '1-2 biji setiap 6 jam jika demam',
        'cat_antipyretic' => 'Antipiretik / Analgesik',
        'status_adequate' => 'Mencukupi',
        'ors_dosage_desc' => '1 paket dalam 250ml air selepas cirit',
        'cat_electrolyte' => 'Elektrolit',
        'col_stock_status' => 'Status Stok',
        'col_standard_dosage' => 'Dos Lazim',
        'col_category' => 'Kategori',
        'col_med_name' => 'Nama Ubat',
        'med_stock_title' => 'Senarai Stok Ubat Rawatan Awal',
        'mood_guide_desc' => 'Kejadian wabak atau bencana kesihatan boleh meningkatkan tahap keresahan komuniti. Pantau tanda-tanda keletihan melampau, insomnia, atau ketegangan emosi pada pesakit dan ahli keluarga mereka.',
        'mood_guide_title' => 'Panduan Kesihatan Psikososial Komuniti',
        'lbl_moderate' => 'Sederhana',
        'lbl_ideal' => 'Ideal',
        'lbl_attention' => 'Perhatian',
        'water_zone_alert' => 'Bekalan air bersih dan larutan ORS tersedia di semua pos rawatan komuniti.',
        'water_zone_status_title' => 'Status Hidrasi Mengikut Zon',
        'water_target_guide' => 'Pesakit dewasa disyorkan mengambil sekurang-kurangnya 2.0L - 2.5L (8-10 gelas) air bersih setiap hari, terutamanya semasa rawatan cirit-birit atau demam.',
        'water_daily_target_title' => 'Sasaran Hidrasi Harian',
        'lbl_now' => 'Sekarang',
        'ph_chat_message' => 'Tulis mesej atau arahan klinikal...',
        'lbl_patient_prefix' => 'Pesakit',
        'chat_status_active' => 'Aktif Sekarang',
        'chat_channel_title' => 'Saluran Bantuan Kesihatan Komuniti',
        'unit_people' => 'Orang',
        'col_total_members' => 'Jumlah Ahli',
        'col_address_zone' => 'Alamat / Zon',
        'col_head_family' => 'Ketua Keluarga',
        'no_families_found' => 'Tiada rekod keluarga',
        'no_patients_found' => 'Tiada rekod pesakit',
        'tab_family_info' => 'Maklumat Keluarga',
        'tab_registered_patients' => 'Pesakit Berdaftar',
        'ph_poster_title' => 'Poster Kesihatan',
        'no_posters_desc' => 'Poster infografik kesihatan akan dipaparkan di sini apabila diterbitkan.',
        'no_posters_published' => 'Tiada Poster Diterbitkan',
        'no_announcements_desc' => 'Semua maklumat rasmi akan dipaparkan di sini apabila diterbitkan oleh pentadbir.',
        'no_announcements_published' => 'Tiada Pengumuman Diterbitkan',
        'btn_submit_triage' => 'Daftar & Hantar Triaj',
        'lbl_manual_override' => 'Pengubahsuaian Manual:',
        'triage_green_desc' => 'Kes Biasa / Bukan Kecemasan',
        'triage_green_short' => 'HIJAU',
        'triage_result_title' => 'Keputusan Triaj',
        'ph_complaint_notes' => 'Catatan aduan utama pesakit, sejarah alahan, atau ubat yang diambil...',
        'sec_complaint_notes' => 'Aduan & Catatan Klinikal',
        'sym_pain' => 'Sakit Perut Kuat',
        'sym_breath' => 'Sesak Nafas',
        'sym_vomit' => 'Muntah Berulang',
        'sym_diarrhea' => 'Cirit-birit Kerap',
        'sym_fever' => 'Demam Tinggi',
        'lbl_symptoms_experienced' => 'Gejala Yang Dialami:',
        'vital_glucose' => 'Glukosa Darah (mmol/L)',
        'vital_bp' => 'Tekanan Darah (BP)',
        'vital_temp' => 'Suhu Badan',
        'sec_vitals_symptoms' => 'Tanda Vital & Gejala Akut',
        'gender_female' => 'Perempuan',
        'gender_male' => 'Lelaki',
        'col_age' => 'Umur (Tahun)',
        'ph_patient_name' => 'Nama pesakit',
        'sec_patient_info' => 'Maklumat Pesakit',
        'error_registration' => 'Ralat pendaftaran: ',
        'error_enter_name' => 'Sila masukkan nama pesakit.',
        // Navigation & Portals
        'nav_dashboard'         => 'Dashboard',
        'nav_triage'            => 'Triaj',
        'nav_triage_list'       => 'Senarai Triaj',
        'nav_triage_counter'    => 'Kaunter Triaj',
        'nav_patients'          => 'Pesakit',
        'nav_personnel'         => 'Kakitangan & Sukarelawan',
        'nav_announcements'     => 'Pengumuman',
        'nav_posters'           => 'Galeri Poster',
        'nav_family'            => 'Maklumat Keluarga',
        'nav_screening'         => 'Saringan Kesihatan',
        'nav_livechat'          => 'Live Chat',
        'nav_ask_doctor'        => 'Tanya Doktor',
        'nav_health_module'     => 'Modul Kesihatan',
        'nav_water'             => 'Air Minum',
        'nav_bristol'           => 'Skala Bristol',
        'nav_mood'              => 'Jurnal Mood',
        'nav_medicine'          => 'Ubat-Ubatan',
        'nav_settings'          => 'Tetapan',
        'nav_logout'            => 'Log Keluar',
        'nav_admin_portal'      => 'Portal Pentadbir',
        'nav_doctor_portal'     => 'Portal Doktor',
        'nav_volunteer_portal'  => 'Portal Sukarelawan',
        'nav_patient_portal'    => 'Portal Pesakit',

        // Roles
        'role_admin'            => 'Pentadbir Sistem',
        'role_doctor'           => 'Pegawai Perubatan / Doktor',
        'role_volunteer'        => 'Sukarelawan',
        'role_user'             => 'Pesakit / Komuniti',

        // Common Buttons & Actions
        'btn_all'               => 'Semua',
        'btn_add'               => 'Tambah',
        'btn_save'              => 'Simpan',
        'btn_edit'              => 'Kemaskini',
        'btn_delete'            => 'Padam',
        'btn_cancel'            => 'Batal',
        'btn_search'            => 'Cari',
        'btn_filter'            => 'Tapis',
        'btn_export_csv'        => 'Eksport CSV',
        'btn_view_all'          => 'Lihat Semua',
        'btn_quick_actions'     => 'Tindakan Pantas',
        'btn_send'              => 'Hantar',
        'btn_close'             => 'Tutup',
        'btn_back'              => 'Kembali',
        'btn_submit'            => 'Hantar Borang',
        'search_placeholder'    => 'Cari nama atau IC...',

        // Table Columns
        'col_hash'              => '#',
        'col_patient_name'      => 'Nama Pesakit',
        'col_name'              => 'Nama',
        'col_email'             => 'E-mel',
        'col_role'              => 'Peranan',
        'col_ic'                => 'No. IC / ID',
        'col_level'             => 'Tahap Triaj',
        'col_vitals'            => 'Tanda Vital',
        'col_complaint'         => 'Aduan Utama',
        'col_time'              => 'Masa',
        'col_status'            => 'Status',
        'col_triaged_by'        => 'Ditapis Oleh',
        'col_date_reg'          => 'Tarikh Daftar',
        'col_action'            => 'Tindakan',
        'col_gender'            => 'Jantina',
        'col_phone'             => 'No. Telefon',
        'col_dob'               => 'Tarikh Lahir',

        // Status & Triage Levels
        'triage_red'            => 'Merah (Kritikal)',
        'triage_yellow'         => 'Kuning (Separa Kritikal)',
        'triage_green'          => 'Hijau (Biasa)',
        'status_active'         => 'Aktif',
        'status_waiting'        => 'Menunggu',
        'status_completed'      => 'Selesai',
        'status_draft'          => 'Draf',
        'status_published'      => 'Diterbitkan',

        // Page Specific Titles & Subtitles
        'page_triage_list_title'=> 'Senarai Triaj Langsung',
        'page_triage_list_sub'  => 'Pantau dan tapis tahap keseriusan pesakit secara masa nyata',
        'page_triage_add_title' => 'Kaunter Triaj — Pendaftaran',
        'page_triage_add_sub'   => 'Borang penilaian klinikal dan saringan tanda vital pesakit',
        'page_personnel_title'  => 'Kakitangan & Sukarelawan',
        'page_personnel_sub'    => 'Senarai petugas perubatan, jururawat dan sukarelawan aktif',
        'page_patients_title'   => 'Pendaftaran Pesakit',
        'page_patients_sub'     => 'Senarai dan rekod profil pesakit komuniti',
        'page_announcements_title'=> 'Pengumuman Komuniti',
        'page_announcements_sub'=> 'Maklumat terkini dan hebahan rasmi',
        'page_posters_title'    => 'Galeri Poster Kesihatan',
        'page_posters_sub'      => 'Infografik dan panduan kesihatan komuniti',
        'page_family_title'     => 'Maklumat Keluarga Komuniti',
        'page_family_sub'       => 'Senarai rekod isi rumah dan ahli keluarga',
        'page_screening_title'  => 'Saringan Kesihatan Komuniti',
        'page_screening_sub'    => 'Maklum balas borang saringan kesihatan atas talian',
        'page_water_title'      => 'Pemantauan Air Minum',
        'page_water_sub'        => 'Log pengambilan air harian dan sasaran hidrasi',
        'page_bristol_title'    => 'Skala Bentuk Najis Bristol',
        'page_bristol_sub'      => 'Panduan dan pemantauan kesihatan pencernaan',
        'page_mood_title'       => 'Jurnal Kesejahteraan Mood',
        'page_mood_sub'         => 'Pemantauan emosi, stres dan kesihatan mental',
        'page_medicine_title'   => 'Peringatan & Rekod Ubat',
        'page_medicine_sub'     => 'Jadual pematuhan dos dan ubat preskripsi',
        'page_livechat_title'   => 'Live Chat Perubatan',
        'page_livechat_sub'     => 'Saluran komunikasi langsung antara pesakit dan petugas',

        // Dashboard Common
        'doc_dash_title'        => 'Dashboard Doktor',
        'doc_dash_welcome'      => 'Selamat bertugas',
        'doc_dash_subtitle'     => 'Pantau barisan giliran triaj & tindakan klinikal.',
        'doc_btn_new_triage'    => 'Daftar Triaj Baharu',
        'doc_stat_red'          => 'Kritikal (Red) Menunggu',
        'doc_stat_yellow'       => 'Urgent (Yellow) Menunggu',
        'doc_stat_green'        => 'Standard (Green) Menunggu',
        'doc_stat_patients'     => 'Jumlah Pesakit Berdaftar',
        'doc_urgent_queue'      => 'Barisan Tindakan Segera (Urgent Action Queue)',
        'doc_no_records'        => 'Tiada pesakit sedang menunggu dalam barisan triaj.',
        'doc_btn_register_walkin'=> 'Daftar Pesakit / Walk-in',
        'doc_btn_check_family'  => 'Semak Maklumat Keluarga',
        'doc_btn_announcements' => 'Pengumuman Komuniti',
        'doc_team_comms'        => 'Komunikasi Pasukan',
        'doc_open_chat'         => 'Buka Chat',
        'doc_send_message'      => 'Hantar Mesej Pasukan',

        'admin_dash_title'      => 'Dashboard Pentadbir',
        'admin_dash_subtitle'   => 'Ringkasan operasi dan pemantauan sistem SeDaP',
        'admin_stat_patients'   => 'Jumlah Pesakit',
        'admin_stat_triage_today'=> 'Triaj Hari Ini',
        'admin_stat_announcements'=> 'Pengumuman Aktif',
        'admin_stat_staff'      => 'Petugas & Sukarelawan',
        'admin_recent_triage'   => 'Rekod Triaj Terkini',
        'admin_btn_new_triage'  => 'Daftar Triaj Baru',
        'admin_btn_patients'    => 'Pengurusan Pesakit',
        'admin_btn_staff'       => 'Pengurusan Kakitangan',
        'admin_btn_posters'     => 'Galeri Poster',
        'admin_btn_settings'    => 'Tetapan Sistem',

        // Settings Page
        'settings_title'        => 'Tetapan Akaun',
        'settings_subtitle'     => 'Urus penampilan, bahasa dan keselamatan akaun sistem',
        'settings_appearance'   => 'Penampilan',
        'settings_dark_mode'    => 'Mod Gelap (Dark Mode)',
        'settings_dark_desc'    => 'Tukar antara tema cerah dan tema gelap',
        'settings_lang'         => 'Bahasa (Language)',
        'settings_lang_select'  => 'Pilihan Bahasa',
        'settings_lang_desc'    => 'Pilih bahasa paparan antaramuka sistem',
        'settings_change_pw'    => 'Tukar Kata Laluan',
        'settings_current_pw'   => 'Kata Laluan Semasa',
        'settings_new_pw'       => 'Kata Laluan Baharu',
        'settings_confirm_pw'   => 'Sahkan Kata Laluan Baharu',
        'settings_btn_update_pw'=> 'Kemas Kini Kata Laluan',
        'settings_account_info' => 'Maklumat Akaun',
        'settings_profile'      => 'Kemaskini Profil',
        'settings_name'         => 'Nama Penuh',
        'settings_email'        => 'Alamat E-mel',
        'settings_phone'        => 'Nombor Telefon',
        'settings_username'     => 'Nama Pengguna',
        'settings_dob'          => 'Tarikh Lahir',
        'settings_weight'       => 'Berat Badan (kg)',
        'settings_btn_save'     => 'Simpan Perubahan',
        'settings_confirm_logout'=> 'Adakah anda pasti mahu log keluar?',
    ],

    'en' => [
        // Navigation & Portals
        'nav_dashboard'         => 'Dashboard',
        'nav_triage'            => 'Triage',
        'nav_triage_list'       => 'Triage List',
        'nav_triage_counter'    => 'Triage Counter',
        'nav_patients'          => 'Patients',
        'nav_personnel'         => 'Staff & Volunteers',
        'nav_announcements'     => 'Announcements',
        'nav_posters'           => 'Poster Gallery',
        'nav_family'            => 'Family Info',
        'nav_screening'         => 'Health Screening',
        'nav_livechat'          => 'Live Chat',
        'nav_ask_doctor'        => 'Ask Doctor',
        'nav_health_module'     => 'Health Modules',
        'nav_water'             => 'Water Tracker',
        'nav_bristol'           => 'Bristol Scale',
        'nav_mood'              => 'Mood Journal',
        'nav_medicine'          => 'Medication',
        'nav_settings'          => 'Settings',
        'nav_logout'            => 'Log Out',
        'nav_admin_portal'      => 'Admin Portal',
        'nav_doctor_portal'     => 'Doctor Portal',
        'nav_volunteer_portal'  => 'Volunteer Portal',
        'nav_patient_portal'    => 'Patient Portal',

        // Roles
        'role_admin'            => 'System Administrator',
        'role_doctor'           => 'Medical Officer / Doctor',
        'role_volunteer'        => 'Volunteer',
        'role_user'             => 'Patient / Community',

        // Common Buttons & Actions
        'btn_all'               => 'All',
        'btn_add'               => 'Add New',
        'btn_save'              => 'Save',
        'btn_edit'              => 'Edit',
        'btn_delete'            => 'Delete',
        'btn_cancel'            => 'Cancel',
        'btn_search'            => 'Search',
        'btn_filter'            => 'Filter',
        'btn_export_csv'        => 'Export CSV',
        'btn_view_all'          => 'View All',
        'btn_quick_actions'     => 'Quick Actions',
        'btn_send'              => 'Send',
        'btn_close'             => 'Close',
        'btn_back'              => 'Back',
        'btn_submit'            => 'Submit Form',
        'search_placeholder'    => 'Search name or IC...',

        // Table Columns
        'col_hash'              => '#',
        'col_patient_name'      => 'Patient Name',
        'col_name'              => 'Name',
        'col_email'             => 'Email',
        'col_role'              => 'Role',
        'col_ic'                => 'IC / ID No.',
        'col_level'             => 'Triage Level',
        'col_vitals'            => 'Vital Signs',
        'col_complaint'         => 'Chief Complaint',
        'col_time'              => 'Time',
        'col_status'            => 'Status',
        'col_triaged_by'        => 'Triaged By',
        'col_date_reg'          => 'Registered Date',
        'col_action'            => 'Action',
        'col_gender'            => 'Gender',
        'col_phone'             => 'Phone Number',
        'col_dob'               => 'Date of Birth',

        // Status & Triage Levels
        'triage_red'            => 'Red (Critical)',
        'triage_yellow'         => 'Yellow (Semi-Critical)',
        'triage_green'          => 'Green (Standard)',
        'status_active'         => 'Active',
        'status_waiting'        => 'Waiting',
        'status_completed'      => 'Completed',
        'status_draft'          => 'Draft',
        'status_published'      => 'Published',

        // Page Specific Titles & Subtitles
        'page_triage_list_title'=> 'Live Triage List',
        'page_triage_list_sub'  => 'Real-time monitoring of patient triage and severity',
        'page_triage_add_title' => 'Triage Counter — Registration',
        'page_triage_add_sub'   => 'Clinical evaluation and vital signs screening form',
        'page_personnel_title'  => 'Staff & Volunteers',
        'page_personnel_sub'    => 'Directory of active medical personnel and volunteers',
        'page_patients_title'   => 'Patient Registration',
        'page_patients_sub'     => 'Community patient records and profile directory',
        'page_announcements_title'=> 'Community Announcements',
        'page_announcements_sub'=> 'Latest updates and official broadcasts',
        'page_posters_title'    => 'Health Poster Gallery',
        'page_posters_sub'      => 'Infographics and health education guides',
        'page_family_title'     => 'Community Family Information',
        'page_family_sub'       => 'Household census and family member records',
        'page_screening_title'  => 'Community Health Screening',
        'page_screening_sub'    => 'Online health screening responses and assessments',
        'page_water_title'      => 'Water Intake Tracker',
        'page_water_sub'        => 'Daily hydration logs and personal water target',
        'page_bristol_title'    => 'Bristol Stool Form Scale',
        'page_bristol_sub'      => 'Digestive health monitoring and educational guide',
        'page_mood_title'       => 'Mood & Wellness Journal',
        'page_mood_sub'         => 'Daily emotion, stress level, and mental wellness tracking',
        'page_medicine_title'   => 'Medication & Reminders',
        'page_medicine_sub'     => 'Dosage adherence schedule and prescription log',
        'page_livechat_title'   => 'Medical Live Chat',
        'page_livechat_sub'     => 'Direct real-time consultation between patients and medical staff',

        // Dashboard Common
        'doc_dash_title'        => 'Doctor Dashboard',
        'doc_dash_welcome'      => 'Welcome on duty',
        'doc_dash_subtitle'     => 'Monitor triage queue and clinical actions.',
        'doc_btn_new_triage'    => 'New Triage Entry',
        'doc_stat_red'          => 'Critical (Red) Waiting',
        'doc_stat_yellow'       => 'Urgent (Yellow) Waiting',
        'doc_stat_green'        => 'Standard (Green) Waiting',
        'doc_stat_patients'     => 'Total Registered Patients',
        'doc_urgent_queue'      => 'Urgent Action Queue',
        'doc_no_records'        => 'No patients currently waiting in triage queue.',
        'doc_btn_register_walkin'=> 'Register Patient / Walk-in',
        'doc_btn_check_family'  => 'Review Family Information',
        'doc_btn_announcements' => 'Community Announcements',
        'doc_team_comms'        => 'Team Communications',
        'doc_open_chat'         => 'Open Chat',
        'doc_send_message'      => 'Send Team Message',

        'admin_dash_title'      => 'Admin Dashboard',
        'admin_dash_subtitle'   => 'Operational summary and SeDaP system monitoring',
        'admin_stat_patients'   => 'Total Patients',
        'admin_stat_triage_today'=> "Today's Triage",
        'admin_stat_announcements'=> 'Active Announcements',
        'admin_stat_staff'      => 'Staff & Volunteers',
        'admin_recent_triage'   => 'Recent Triage Records',
        'admin_btn_new_triage'  => 'New Triage Entry',
        'admin_btn_patients'    => 'Patient Management',
        'admin_btn_staff'       => 'Personnel Management',
        'admin_btn_posters'     => 'Poster Gallery',
        'admin_btn_settings'    => 'System Settings',

        // Settings Page
        'settings_title'        => 'Account Settings',
        'settings_subtitle'     => 'Manage appearance, language, and system security',
        'settings_appearance'   => 'Appearance',
        'settings_dark_mode'    => 'Dark Mode',
        'settings_dark_desc'    => 'Toggle between light and dark themes',
        'settings_lang'         => 'Language (Bahasa)',
        'settings_lang_select'  => 'Language Selection',
        'settings_lang_desc'    => 'Choose system interface display language',
        'settings_change_pw'    => 'Change Password',
        'settings_current_pw'   => 'Current Password',
        'settings_new_pw'       => 'New Password',
        'settings_confirm_pw'   => 'Confirm New Password',
        'settings_btn_update_pw'=> 'Update Password',
        'settings_account_info' => 'Account Information',
        'settings_profile'      => 'Update Profile',
        'settings_name'         => 'Full Name',
        'settings_email'        => 'Email Address',
        'settings_phone'        => 'Phone Number',
        'settings_username'     => 'Username',
        'settings_dob'          => 'Date of Birth',
        'settings_weight'       => 'Body Weight (kg)',
        'settings_btn_save'     => 'Save Changes',
        'settings_confirm_logout'=> 'Are you sure you want to log out?',
    ]
];

function __($key, $default = '') {
    global $TRANSLATIONS, $_SESSION_LANG;
    return $TRANSLATIONS[$_SESSION_LANG][$key] ?? ($default ?: $key);
}
